# Generated by Django 5.0.1 on 2024-07-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='access_code',
            field=models.CharField(default='000000000', max_length=9, unique=True),
        ),
    ]
