# Generated by Django 5.1.4 on 2026-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ_donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organdonation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('matched', 'Matched'), ('engaged', 'Engaged'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('engaged', 'Engaged'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
