# Generated by Django 5.0.1 on 2024-07-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('medication', models.JSONField()),
                ('additional_precautions', models.TextField()),
            ],
        ),
    ]
