# Generated by Django 5.0.1 on 2024-07-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
