# Generated by Django 5.0.1 on 2024-07-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_delete_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='Medical_registration_proof',
        ),
    ]
