# Generated by Django 5.0.1 on 2024-07-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctorprofile_medical_registration_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='Profile_pic',
            field=models.ImageField(default='doctors_profile_pictures/doctor-img2.png', upload_to='doctors_profile_pictures'),
        ),
    ]
