# Generated by Django 5.0.1 on 2024-07-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctorprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='Profile_pic',
            field=models.ImageField(default='profile_pictures/doctor-img2.png', upload_to='profile_pictures'),
        ),
    ]
